db_name: 'bike_network_analysis'
input_db_name: 'bike_network'
db_user: 'postgres'
db_port: '5432'
db_host: 'localhost'
db_password: 'aneitu'

network_edges: 'osm_edges_export'
network_nodes: 'osm_nodes_export'

socio_fp: "../data/processed/voting_areas.gpkg"
adm_boundaries_fp: "../data/input/adm_boundaries/muni_boundaries.gpkg"

# Define LTS levels to compare
LTS:
- 1
- 2
- 3
- 4

# LTS values for total network
LTS_TOTAL:
- 1
- 2
- 3
- 4
# - 999
# - 0