db_name: 'bike_network_analysis'
input_db_name: 'bike_network'
db_user: 'postgres'
db_port: '5432'
db_host: 'localhost'
db_password: 'aneitu'

CRS: 'EPSG:25832'

network_edges: 'osm_edges_export'
network_nodes: 'osm_nodes_export'


socio_fp: "../data/processed/voting_areas.gpkg"
adm_boundaries_fp: "../data/input/adm_boundaries/muni_boundaries.gpkg"
urban_areas_fp: "../data/input/urban/urban_areas.parquet"

h3_resolution: 8


# Define K values for spatial weights
k_muni: 3
k_socio: 4
k_hex: 6
p_lisa: 0.05  # p-value for LISA