db_name: 'bike_network_analysis'
input_db_name: 'bike_network'
db_user: 'postgres'
db_port: '5432'
db_host: 'localhost'
db_password: 'aneitu'

CRS: 'EPSG:25832'

network_edges: 'osm_edges_export'
network_nodes: 'osm_nodes_export'


socio_fp: "../data/processed/voting_areas.gpkg"
muni_boundaries_fp: "../data/input/municipalities/muni_boundaries.gpkg"
urban_areas_fp: "../data/input/urban/urban_areas.parquet"
pop_fp_1: "../data/input/population/GHS_POP_E2020_GLOBE_R2023A_4326_3ss_V1_0_R4_C19/GHS_POP_E2020_GLOBE_R2023A_4326_3ss_V1_0_R4_C19.tif"
pop_fp_2: "../data/input/population/GHS_POP_E2020_GLOBE_R2023A_4326_3ss_V1_0_R4_C20/GHS_POP_E2020_GLOBE_R2023A_4326_3ss_V1_0_R4_C20.tif"


h3_resolution: 8


# Define K values for spatial weights
k_muni: 3
k_socio: 4
k_hex: 6
p_lisa: 0.05  # p-value for LISA

# Distance for evaluation of network reach
reach_dist: 5
all_reach_distances:
- 1
- 2
- 5
- 10
- 15
