name: dk_network_analysis
channels:
  - plotly
  - conda-forge
  - conda
  - defaults
dependencies:
  - affine=2.4.0
  - appnope=0.1.4
  - asttokens=2.4.1
  - attrs=23.2.0
  - aws-c-auth=0.7.16
  - aws-c-cal=0.6.10
  - aws-c-common=0.9.13
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.1
  - aws-c-io=0.14.5
  - aws-c-mqtt=0.10.2
  - aws-c-s3=0.5.2
  - aws-c-sdkutils=0.1.15
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.2
  - aws-sdk-cpp=1.11.267
  - azure-core-cpp=1.11.1
  - azure-storage-blobs-cpp=12.10.0
  - azure-storage-common-cpp=12.5.0
  - blosc=1.21.5
  - branca=0.7.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.27.0
  - ca-certificates=2024.2.2
  - cairo=1.18.0
  - certifi=2024.2.2
  - cfitsio=4.3.1
  - charset-normalizer=3.3.2
  - click=8.1.7
  - click-plugins=1.1.1
  - cligj=0.7.2
  - comm=0.2.1
  - contextily=1.6.0
  - contourpy=1.2.0
  - cycler=0.12.1
  - debugpy=1.8.1
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.6.1
  - fiona=1.9.6
  - folium=0.16.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.49.0
  - freetype=2.12.1
  - freexl=2.0.0
  - gdal=3.8.4
  - geoalchemy2=0.14.6
  - geographiclib=2.0
  - geopandas=0.14.3
  - geopandas-base=0.14.3
  - geopy=2.4.1
  - geos=3.12.1
  - geotiff=1.7.1
  - gettext=0.21.1
  - gflags=2.2.2
  - giflib=5.2.1
  - glog=0.7.0
  - greenlet=3.0.3
  - h3=4.1.0
  - h3-py=3.7.7
  - hdf4=4.2.15
  - hdf5=1.14.3
  - icu=73.2
  - idna=3.6
  - importlib-metadata=7.0.2
  - importlib_metadata=7.0.2
  - ipykernel=6.29.3
  - ipython=8.22.2
  - jedi=0.19.1
  - jinja2=3.1.3
  - joblib=1.3.2
  - json-c=0.17
  - jupyter_client=8.6.0
  - jupyter_core=5.7.1
  - kealib=1.5.3
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240116.1
  - libaec=1.1.2
  - libarchive=3.7.2
  - libarrow=15.0.0
  - libarrow-acero=15.0.0
  - libarrow-dataset=15.0.0
  - libarrow-flight=15.0.0
  - libarrow-flight-sql=15.0.0
  - libarrow-gandiva=15.0.0
  - libarrow-substrait=15.0.0
  - libblas=3.9.0
  - libboost-headers=1.84.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.5.0
  - libcxx=16.0.6
  - libdeflate=1.19
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.1
  - libffi=3.4.2
  - libgdal=3.8.4
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libglib=2.78.4
  - libgoogle-cloud=2.22.0
  - libgoogle-cloud-storage=2.22.0
  - libgrpc=1.62.1
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libllvm16=16.0.6
  - libnetcdf=4.9.2
  - libnghttp2=1.58.0
  - libopenblas=0.3.26
  - libparquet=15.0.0
  - libpng=1.6.43
  - libpq=16.2
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.1.0
  - libsqlite=3.45.1
  - libssh2=1.11.0
  - libthrift=0.19.0
  - libtiff=4.6.0
  - libutf8proc=2.8.0
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.12.5
  - libzip=1.10.1
  - libzlib=1.2.13
  - llvm-openmp=18.1.4
  - llvmlite=0.42.0
  - lz4-c=1.9.4
  - lzo=2.10
  - mapclassify=2.6.1
  - markupsafe=2.1.5
  - matplotlib-base=3.8.3
  - matplotlib-inline=0.1.6
  - mercantile=1.2.1
  - minizip=4.0.5
  - munkres=1.1.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - networkx=3.2.1
  - nspr=4.35
  - nss=3.98
  - numba=0.59.1
  - numpy=1.26.4
  - openjpeg=2.5.2
  - openssl=3.3.0
  - orc=1.9.2
  - packaging=24.0
  - pandas=2.2.1
  - parso=0.8.3
  - patsy=0.5.6
  - pcre2=10.43
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.2.0
  - pip=24.0
  - pixman=0.43.4
  - platformdirs=4.2.0
  - plotly=5.21.0
  - plotly_express=0.4.0
  - poppler=24.02.0
  - poppler-data=0.4.12
  - postgresql=16.2
  - proj=9.3.1
  - prompt-toolkit=3.0.42
  - psutil=5.9.8
  - psycopg2=2.9.9
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=15.0.0
  - pygments=2.17.2
  - pyparsing=3.1.2
  - pyproj=3.6.1
  - pysocks=1.7.1
  - python=3.12.2
  - python-dateutil=2.9.0
  - python-tzdata=2024.1
  - python_abi=3.12
  - pytz=2024.1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - rasterio=1.3.9
  - re2=2023.09.01
  - readline=8.2
  - requests=2.31.0
  - rtree=1.2.0
  - scikit-learn=1.4.1.post1
  - scipy=1.12.0
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=69.1.1
  - shapely=2.0.3
  - six=1.16.0
  - snappy=1.1.10
  - snuggs=1.4.7
  - sqlalchemy=2.0.28
  - sqlite=3.45.1
  - stack_data=0.6.2
  - statsmodels=0.14.1
  - tenacity=8.2.3
  - threadpoolctl=3.3.0
  - tiledb=2.20.1
  - tk=8.6.13
  - tornado=6.4
  - traitlets=5.14.1
  - typing-extensions=4.10.0
  - typing_extensions=4.10.0
  - tzcode=2024a
  - tzdata=2024a
  - uriparser=0.9.7
  - urllib3=2.2.1
  - wcwidth=0.2.13
  - wheel=0.42.0
  - xerces-c=3.2.5
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xyzservices=2023.10.1
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - fastjsonschema=
      - jsonschema=
      - jsonschema-specifications=
      - kaleido=
      - nbformat=
      - referencing=
      - rpds-py=
